apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: retry-hpa
  namespace: djqueue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: retry-orchestrator

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization